services:
  keycloak:
    image: keycloak/keycloak:24.0
    container_name: oauth
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=pg
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_CORS=true                  # Enable CORS
      - KEYCLOAK_CORS_ALLOWED_ORIGINS=http://yourfrontend.com # Allow specific origin (replace with your frontend's URL)
      - KEYCLOAK_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS  # Allow specific HTTP methods
      - KEYCLOAK_CORS_ALLOWED_HEADERS=Authorization,Content-Type    # Allow specific headers
    command: [ "start-dev" ]
    depends_on:
      - pg


  pg:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
