services:
  nginx:
    image: nginx:alpine
    container_name: nginx-conf
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - webnet

  api:
    image: node:alpine
    container_name: nest-api
    working_dir: /usr/src/app
    volumes:
      - ./nest-app:/usr/src/app
    command: sh -c "yarn start dev"
    ports:
      - "8080:8080" 
    depends_on:
      - pg
    networks:
      - webnet

  pg:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  pg-data:

networks:
  webnet:
    driver: bridge
