services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel_app:/var/www/laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./laravel_app:/var/www/laravel
    
  mysql:
    image: mysql:latest
    env_file:
      - env/mysql.env
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./laravel_app:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./laravel_app:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]


volumes:
  db_data:

    
